name: octri_monitoring
description: Standalone application monitoring and error reporting for Dart.
version: 1.0.1
homepage: https://octri.dev
documentation: https://docs.octri.dev/docs
issue_tracker: https://octri.dev/support
repository: https://github.com/octridev/octri-dart
topics:
  - monitoring
  - observability
  - error-tracking
environment:
  sdk: '>=3.2.0 <4.0.0'
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
